export const FETCH_CARS_STARTED = 'FETCH_CARS_STARTED';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILED = 'FETCH_CARS_FAILED';

export const POST_CAR_STARTED = 'POST_CAR_START';
export const POST_CAR_SUCCESS = 'POST_CAR_SUCCESS';
export const POST_CAR_FAILED = 'POST_CAR_FAILED';

export const SET_PROGRESS = 'SET_PROGRESS';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';

export const SIGNUP_STARTED = 'SIGNUP_STARTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';